import numpy as np, sys, os
sys.path.insert(0, '.')
os.makedirs('figures', exist_ok=True)
os.makedirs('manuscript', exist_ok=True)

from dolfinx import fem
import ufl
from micrograd import GradientGeneratorOptimizer
from micrograd.christmas_tree import create_christmas_tree_density, simulate_christmas_tree

Lx, Ly = 2000e-6, 500e-6
opt = GradientGeneratorOptimizer(Lx=Lx, Ly=Ly, nx=20, ny=5,
                                 target_expr=lambda x: x[1]/Ly,
                                 w_f=1e-7, w_c=5e4, V_star=0.5)
opt.run(max_iter=400, beta_continuation=[1,2,4,8,16,32,64], move=0.05)

ft      = opt.boundary_data["facet_tag"]
out     = opt.boundary_data["outlet"]
fd      = opt.msh.topology.dim - 1
ds_out  = ufl.Measure("ds", domain=opt.msh, subdomain_data=ft, subdomain_id=3)
n       = ufl.FacetNormal(opt.msh)

Vc   = opt.c_h.function_space
dofs = fem.locate_dofs_topological(Vc, fd, out)
y_out= opt.msh.geometry.x[dofs, 1]
c_out= opt.c_h.x.array[dofs]
idx  = np.argsort(y_out); y_s, c_s = y_out[idx], c_out[idx]
rmse = float(np.sqrt(np.mean((np.clip(c_s,0,1) - y_s/Ly)**2)))

Q = float(abs(fem.assemble_scalar(fem.form(ufl.dot(opt.u_h, n)*ds_out))))
R = 1000.0/Q if Q > 1e-30 else float('inf')
u_arr = opt.u_h.x.array
U_max = float(np.max(np.sqrt(u_arr[::2]**2 + u_arr[1::2]**2)))
final_J   = float(opt.history[-1, 2])
n_iter    = int(opt.history[-1, 0]) + 1
vol_frac  = float(opt.V_star_final)

# Christmas tree comparison
rho_tree = create_christmas_tree_density(opt.msh, Lx=opt.Lx, Ly=opt.Ly)
tree_res = simulate_christmas_tree(opt.msh, opt.boundary_data, rho_tree, opt.target_expr)
c_tree   = tree_res["concentration"]
dofs_t   = fem.locate_dofs_topological(c_tree.function_space, fd, out)
y_tree   = opt.msh.geometry.x[dofs_t, 1]
c_tree_v = c_tree.x.array[dofs_t]
idx_t    = np.argsort(y_tree)
rmse_tree= float(np.sqrt(np.mean((np.clip(c_tree_v[idx_t],0,1) - y_tree[idx_t]/Ly)**2)))
Q_tree   = float(abs(fem.assemble_scalar(fem.form(ufl.dot(tree_res["velocity"], n)*ds_out))))
R_tree   = 1000.0/Q_tree if Q_tree > 1e-30 else float('inf')
reduction= (1 - R/R_tree)*100 if R_tree != float('inf') else 0.0

print(f"RMSE         = {rmse:.4e}")
print(f"Hydraulic R  = {R:.4e} Pa.s/m^3")
print(f"Flow rate Q  = {Q:.4e} m^3/s")
print(f"Max velocity = {U_max:.4e} m/s")
print(f"Final J      = {final_J:.4e}")
print(f"Iterations   = {n_iter}")
print(f"Vol fraction = {vol_frac:.4f}")
print(f"Tree RMSE    = {rmse_tree:.4e}")
print(f"Tree Hyd R   = {R_tree:.4e} Pa.s/m^3")
print(f"Reduction    = {reduction:.1f}%")

lines = [
    "% Auto-generated by generate_macros.py",
    f"\\newcommand{{\\rmseLinear}}{{{rmse:.4f}}}",
    f"\\newcommand{{\\hydraulicR}}{{{R:.3e}}}",
    f"\\newcommand{{\\flowRateQ}}{{{Q:.3e}}}",
    f"\\newcommand{{\\uMax}}{{{U_max:.4e}}}",
    f"\\newcommand{{\\finalObjective}}{{{final_J:.4e}}}",
    f"\\newcommand{{\\nIterations}}{{{n_iter}}}",
    f"\\newcommand{{\\volFrac}}{{{vol_frac:.3f}}}",
    f"\\newcommand{{\\rmseTree}}{{{rmse_tree:.4f}}}",
    f"\\newcommand{{\\Rtree}}{{{R_tree:.3e}}}",
    f"\\newcommand{{\\reductionPercent}}{{{reduction:.1f}}}",
]
open('manuscript/macros.tex','w').write('\n'.join(lines)+'\n')
print(f"\nmacros.tex written to manuscript/macros.tex")
