name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v4
        with:
          auto-update-conda: true
          python-version: "3.10"
          miniforge-variant: Miniforge3
          use-mamba: true

      - name: Create conda environment
        shell: bash -l {0}
        run: |
          mamba env create -f environment.yaml
          conda activate micrograd-env

      - name: Install micrograd
        shell: bash -l {0}
        run: |
          conda activate micrograd-env
          pip install -e .

      - name: Run tests
        shell: bash -l {0}
        run: |
          conda activate micrograd-env
          python -m pytest tests/
